name: PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    if: ${{github.event_name != 'merge_group'}}

    steps:
      # Lint Pull Request information
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v4
        with:
          requireScope: true
          scopes: |-
            core
            github
            components
            lib
            pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
